/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ftc.simplematrix.splining;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;

import org.ejml.equation.Symbol;
import org.ejml.simple.SimpleMatrix;
import  ftc.simplematrix.splining.Vector2;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        List<QSplinePath>spline_xs= new ArrayList<QSplinePath>();
        List<QSplinePath>spline_ys= new ArrayList<QSplinePath>();
        

        // X splines
        QSplinePath splinex=new QSplinePath(0,-24,0,0,2,-7,4,2);
        splinex.makeSpline();

        QSplinePath splinex3=new QSplinePath(2,-7,4,0,3,-12,-3,4); 
        splinex3.makeSpline();

        QSplinePath splinex2=new QSplinePath(3, -12, -7, 0, 4, -36, 0, 0);
        splinex2.makeSpline();


        // y splines
        QSplinePath spliney=new QSplinePath(0,-55,0,0,2,0,8.42,0);
        spliney.makeSpline();

        QSplinePath spliney3=new QSplinePath(2,0,8.42,0,3,24,8.42,0);
        spliney3.makeSpline();


        QSplinePath spliney2=new QSplinePath(3,24,8.42,0,4,48,0,0);
        spliney2.makeSpline();


        // adding the splines to the arraylist
        spline_xs.add(splinex);
        spline_xs.add(splinex3);
        spline_xs.add(splinex2);

        spline_ys.add(spliney);
        spline_ys.add(spliney3);
        spline_ys.add(spliney2);

        JFrame frame = new JFrame("Polynomial Graph");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(2000, 2000);
        frame.add(new GraphPanel(spline_xs,spline_ys));
        frame.setVisible(true);



        
    }
}








